# Generated by Django 4.1.1 on 2022-09-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0003_theatre_catergory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritePlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faviourite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='venue.theatre')),
            ],
        ),
    ]
