# Generated by Django 4.1.1 on 2022-09-10 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venue', '0001_initial'),
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='event_key',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='join', to='venue.theatre'),
        ),
        migrations.AddField(
            model_name='attend',
            name='person_key',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='join', to=settings.AUTH_USER_MODEL),
        ),
    ]
