# Generated by Django 4.1.1 on 2022-09-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Epic', 'Epic'), ('Adult', 'Adult'), ('Nonsense', 'Nonsense'), ('Family&Kids', 'Family&Kids'), ('Mythopoeia', 'Mythopoeia'), ('Romance', 'Romance'), ('Satire', 'Satire'), ('Tragedy', 'Tragedy'), ('Tragicomedy', 'Tragicomedy')], default=None, max_length=100)),
            ],
        ),
    ]
