# Generated by Django 4.1.1 on 2022-09-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('a', 'Comedy'), ('b', 'Drama'), ('c', 'Epic'), ('d', 'Adult'), ('e', 'Nonsense'), ('f', 'Family&Kids'), ('g', 'Mythopoeia'), ('h', 'Romance'), ('i', 'Satire'), ('j', 'Tragedy'), ('k', 'Tragicomedy')], default=None, max_length=50)),
            ],
        ),
    ]
