# Generated by Django 4.1.1 on 2022-09-09 13:05

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=True, max_length=600), size=None)),
                ('genres', models.ManyToManyField(related_name='venue', to='categories.category')),
                ('likes', models.ManyToManyField(blank=True, related_name='location_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
