# Generated by Django 4.1.1 on 2022-09-08 15:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=True, max_length=600), size=None)),
            ],
        ),
    ]
