# Generated by Django 4.1.1 on 2022-09-08 15:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatre',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=True, max_length=600), size=None),
        ),
    ]
