# Generated by Django 4.1.1 on 2022-09-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('venue', '0002_alter_theatre_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='catergory',
            field=models.ManyToManyField(related_name='venue', to='categories.category'),
        ),
    ]
